# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package Erika;
use base qw(Exporter);
use base qw(DynaLoader);
package Erikac;
bootstrap Erika;
package Erika;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package Erika;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package Erika;


############# Class : Erika::Trie ##############

package Erika::Trie;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( Erika );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = Erikac::new_Trie(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        Erikac::delete_Trie($self);
        delete $OWNER{$self};
    }
}

*lookup = *Erikac::Trie_lookup;
*common_prefix_search = *Erikac::Trie_common_prefix_search;
*predictive_search = *Erikac::Trie_predictive_search;
*extract = *Erikac::Trie_extract;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


# ------- VARIABLE STUBS --------

package Erika;

1;
